### ISSUE TITLE
Example Usage Error

### ISSUE THREAD

**Issue by rjdjohnston** [philsturgeon/codeigniter-oauth2#12]
In your example usage section this line:
$user = $provider->get_user_info($token->access_token);

Should be replaced with this:
$user = $provider->get_user_info($token);

**Comment by philsturgeon** [comment]
Please send pull requests when you know how to fix something. You can even click "Edit File" to do this in the browser!

**Comment by rjdjohnston** [comment]
Ah!  Good to know

Pardon the brevity, this message was sent from my iPhone.
